### ISSUE TITLE
Endless Repository

### ISSUE THREAD

**Issue by rmeissn** [boredsquirrel/Flatpak-remotes#1]
I'm not sure if this is an outdated repository or not, but Endless Flatpaks can be added as a repo by (from https://gist.github.com/mwleeds/17e2113c893b412409232ff43e2051f7 ):

```
wget https://origin.ostree.endlessm.com/keys/eos-flatpak-keyring.gpg
flatpak remote-add --gpg-import=eos-flatpak-keyring.gpg eos-apps https://ostree.endlessm.com/ostree/eos-apps
flatpak remote-add --gpg-import=eos-flatpak-keyring.gpg eos-sdk https://ostree.endlessm.com/ostree/eos-sdk
```

**Comment by boredsquirrel** [comment]
Thanks! Please add the repo to your system, use the listed command to list packages, and install an app from the terminal.

It should spit out warnings when there are some.

GUI stores are not useful here.

**Comment by rmeissn** [comment]
There are no warnings when installing a package from the CLI. Software starts and works.

**Comment by boredsquirrel** [comment]
awesome!
